version: 2
jobs:
    build:
        docker:
            - image: ubuntu:16.04
        steps:
            - checkout
            - run:
                name: Install build tools
                command: apt update && apt install -y build-essential libc6-dev-i386
            - run:
                name: Build
                command: make && make install
